# SPDX-FileCopyrightText: 2024 Ben
# SPDX-License-Identifier: BSD-3-Clause
name: bai.py test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    - name: Make test script executable
      run: chmod +x ./test.bash
    - name: List repository files
      run: ls -R
    - name: Run tests
      run: bash -xv ./test.bash

